"use client";
import { useState } from "react";
import HtmlEditor from "@/components/HtmlEditor";
import { PERMISSIONS } from "@/lib/permissions";

const gatewayTypes = ["Mollie", "PayPal", "PayPal_IPN", "PayU", "Stripe"];
const serverTypes = ["CPanel", "Convoy", "DirectAdmin", "DownloadableProducts", "Enhance", "Plesk", "Pterodactyl", "Virtfusion", "Virtualizor"];
const countries = ["France","Belgique","Suisse","Luxembourg","Canada","United Kingdom","Germany","Spain","Italy","Netherlands","Portugal","United States","Other"];
const models = ["User","Product","Order","Service","Invoice","Ticket"];
const propertyTypes = ["Text","Textarea","Number","Email","URL","Password","Select","Checkbox","Date","DateTime"];

function Field({label,children,required=false}:{label:string;children:React.ReactNode;required?:boolean}){return <label><span>{label}{required&&<b style={{color:"#ff6b76"}}>*</b>}</span>{children}</label>}
function SettingsFields({kind,type,initial}:{kind:"gateway"|"server";type:string;initial:any}){
 const fields = kind === "gateway" ? ({
   Mollie:["api_key"], PayPal:["client_id","client_secret","mode"], PayPal_IPN:["receiver_email","ipn_secret"], PayU:["merchant_key","merchant_salt","mode"], Stripe:["publishable_key","secret_key","webhook_secret","mode"]
 } as Record<string,string[]>)[type] || [] : ({
   CPanel:["url","api_token","verify_ssl"], Convoy:["url","api_key","verify_ssl"], DirectAdmin:["url","username","password","verify_ssl"], DownloadableProducts:["storage_path","base_url"], Enhance:["url","api_key","verify_ssl"], Plesk:["url","api_key","verify_ssl"], Pterodactyl:["url","api_key","verify_ssl"], Virtfusion:["url","api_key","verify_ssl"], Virtualizor:["url","api_key","api_password","verify_ssl"]
 } as Record<string,string[]>)[type] || [];
 const labels:Record<string,string>={api_key:"API Key",client_id:"Client ID",client_secret:"Client Secret",mode:"Mode",receiver_email:"Receiver Email",ipn_secret:"IPN Secret",merchant_key:"Merchant Key",merchant_salt:"Merchant Salt",publishable_key:"Publishable Key",secret_key:"Secret Key",webhook_secret:"Webhook Secret",url:"URL",api_token:"API Token",username:"Username",password:"Password",verify_ssl:"Verify SSL",storage_path:"Storage Path",base_url:"Base URL",api_password:"API Password"};
 return <div className="module-settings-grid">{fields.map(key=> key==="mode" ? <Field key={key} label={labels[key]}><select className="input" name={`setting_${key}`} defaultValue={initial?.[key]||"live"}><option value="live">Live</option><option value="test">Test</option></select></Field> : key==="verify_ssl" ? <label className="checkline" key={key}><input type="checkbox" name={`setting_${key}`} value="1" defaultChecked={initial?.[key]!==false}/><span>Verify SSL certificate</span></label> : <Field key={key} label={labels[key]}><input className="input" name={`setting_${key}`} type={/secret|password|api_key|api_token|webhook/.test(key)?"password":"text"} defaultValue={initial?.[key]||""} /></Field>)}</div>
}

export function CustomPropertyForm({initial}:{initial?:any}){
 return <form className="form module-form" action="/api/admin/custom-properties" method="post">{initial&&<input type="hidden" name="id" value={initial.id}/>}<div className="two"><Field label="Name" required><input className="input" name="name" defaultValue={initial?.name||""} required/></Field><Field label="Key" required><input className="input" name="key" defaultValue={initial?.property_key||""} required/></Field></div><div className="two"><Field label="Model" required><select className="input" name="model" defaultValue={initial?.model||""} required><option value="">Sélectionnez une option</option>{models.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Type" required><select className="input" name="type" defaultValue={initial?.type||""} required><option value="">Sélectionnez une option</option>{propertyTypes.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Description"><HtmlEditor name="description" defaultValue={initial?.description||""} placeholder="Description du champ en HTML..." minHeight={190} required={false}/></Field><Field label="Validation"><input className="input" name="validation" defaultValue={initial?.validation||""} placeholder="Ex: max:255, regex:..."/></Field><div className="toggle-panel"><label className="checkline"><input type="checkbox" name="non_editable" value="1" defaultChecked={initial?.non_editable===1}/><span>Non editable</span></label><label className="checkline"><input type="checkbox" name="required" value="1" defaultChecked={initial?.required===1}/><span>Required</span></label><label className="checkline"><input type="checkbox" name="show_on_invoice" value="1" defaultChecked={initial?.show_on_invoice===1}/><span>Show on invoice</span></label></div><div className="form-actions"><button className="btn primary">{initial?"Enregistrer":"Créer"}</button>{!initial&&<button className="btn" name="continue" value="1">Créer &amp; Ajouter un autre</button>}<a className="btn" href="/admin/module/custom-properties">Annuler</a></div></form>
}

export function RoleForm({initial}:{initial?:any}){
 const [filter,setFilter]=useState(""); const [selected,setSelected]=useState<string[]>(Array.isArray(initial?.permissions)?initial.permissions:[]);
 const visible=PERMISSIONS.filter(p=>p.toLowerCase().includes(filter.toLowerCase()));
 const all=selected.includes("All Permissions");
 const toggle=(p:string)=>setSelected(current=>current.includes(p)?current.filter(x=>x!==p):[...current,p]);
 const toggleAll=()=>setSelected(current=>current.includes("All Permissions")?[]:[...PERMISSIONS]);
 return <form className="form module-form" action="/api/admin/roles" method="post">{initial&&<input type="hidden" name="id" value={initial.id}/>}<Field label="Name" required><input className="input" name="name" defaultValue={initial?.name||""} required/></Field><div><div className="module-label">Permissions</div><input className="input" placeholder="Commencez à taper pour rechercher..." value={filter} onChange={e=>setFilter(e.target.value)}/><button type="button" className="link-button" onClick={toggleAll}>{all?"Désélectionner tout":"Sélectionner tout"}</button>{selected.map(p=><input type="hidden" name="permissions" value={p} key={`selected-${p}`}/>) }<div className="permission-grid">{visible.map(p=><label className="permission-item" key={p}><input type="checkbox" checked={selected.includes(p)} onChange={()=>toggle(p)}/><span>{p}</span></label>)}</div></div><div className="form-actions"><button className="btn primary">{initial?"Enregistrer":"Créer"}</button>{!initial&&<button className="btn" name="continue" value="1">Créer &amp; Ajouter un autre</button>}<a className="btn" href="/admin/module/roles">Annuler</a></div></form>
}

export function TaxRateForm({initial}:{initial?:any}){return <form className="form module-form" action="/api/admin/tax-rates" method="post">{initial&&<input type="hidden" name="id" value={initial.id}/>}<div className="two"><Field label="Name" required><input className="input" name="name" defaultValue={initial?.name||""} placeholder="Ex: TVA Standard" required/></Field><Field label="Rate" required><div className="suffix-input"><input className="input" type="number" step="0.01" min="0" max="100" name="rate" defaultValue={initial?.rate??""} placeholder="20.00" required/><span>%</span></div></Field></div><Field label="Country" required><select className="input" name="country" defaultValue={initial?.country||""} required><option value="">Sélectionnez une option</option>{countries.map(x=><option key={x}>{x}</option>)}</select></Field><div className="form-actions"><button className="btn primary">{initial?"Enregistrer":"Créer"}</button>{!initial&&<button className="btn" name="continue" value="1">Créer &amp; Ajouter un autre</button>}<a className="btn" href="/admin/module/tax-rates">Annuler</a></div></form>}

export function GatewayForm({initial}:{initial?:any}){const[type,setType]=useState(initial?.gateway_type||""); let settings:any={}; try{settings=initial?.settings?JSON.parse(initial.settings):{}}catch{} return <form className="form module-form" action="/api/admin/gateways" method="post">{initial&&<input type="hidden" name="id" value={initial.id}/>}<div className="two"><Field label="Name" required><input className="input" name="name" defaultValue={initial?.name||""} placeholder="Enter the name of the gateway" required/></Field><Field label="Gateway" required><select className="input" name="gateway_type" value={type} onChange={e=>setType(e.target.value)} required><option value="">Select the type of the gateway</option>{gatewayTypes.map(x=><option key={x}>{x}</option>)}</select></Field></div><section className="module-settings"><h2>Gateway Settings</h2><p>Specific settings for the selected gateway</p>{type?<SettingsFields kind="gateway" type={type} initial={settings}/>:<div className="empty">Sélectionnez un type de gateway pour afficher ses paramètres.</div>}</section><label className="checkline"><input type="checkbox" name="enabled" value="1" defaultChecked={initial?.enabled!==0}/><span>Enabled</span></label><div className="form-actions"><button className="btn primary">{initial?"Enregistrer":"Créer"}</button>{!initial&&<button className="btn" name="continue" value="1">Créer &amp; Ajouter un autre</button>}<a className="btn" href="/admin/module/gateways">Annuler</a></div></form>}

export function ServerForm({initial}:{initial?:any}){const[type,setType]=useState(initial?.type||""); let settings:any={}; try{settings=initial?.settings?JSON.parse(initial.settings):{}}catch{} return <form className="form module-form" action="/api/admin/servers" method="post">{initial&&<input type="hidden" name="id" value={initial.id}/>}<div className="two"><Field label="Name" required><input className="input" name="name" defaultValue={initial?.name||""} placeholder="Enter the name of the server" required/></Field><Field label="Server" required><select className="input" name="type" value={type} onChange={e=>setType(e.target.value)} required><option value="">Select the type of the server</option>{serverTypes.map(x=><option key={x}>{x}</option>)}</select></Field></div><section className="module-settings"><h2>Server Settings</h2><p>Specific settings for the selected server</p>{type?<SettingsFields kind="server" type={type} initial={settings}/>:<div className="empty">Sélectionnez un type de serveur pour afficher ses paramètres.</div>}</section><label className="checkline"><input type="checkbox" name="enabled" value="1" defaultChecked={initial?.enabled!==0}/><span>Enabled</span></label><div className="form-actions"><button className="btn primary">{initial?"Enregistrer":"Créer"}</button>{!initial&&<button className="btn" name="continue" value="1">Créer &amp; Ajouter un autre</button>}<a className="btn" href="/admin/module/servers">Annuler</a></div></form>}
