"use client";
import {useMemo,useState} from "react";
export default function OrderForm({users,products,currencies,plans}:{users:any[],products:any[],currencies:any[],plans:any[]}){
 const [services,setServices]=useState([{productId:"",planId:"",quantity:"1",price:"",subscriptionId:""}]);
 const add=()=>setServices([...services,{productId:"",planId:"",quantity:"1",price:"",subscriptionId:""}]);
 const remove=(i:number)=>setServices(services.filter((_,x)=>x!==i));
 const selected=(i:number)=>products.find(p=>String(p.id)===services[i].productId);
 const payload=services.map(s=>{const p=products.find(x=>String(x.id)===s.productId),pl=plans.find(x=>String(x.id)===s.planId);return {...s,productId:Number(s.productId),productName:p?.name||"",plan:pl?.name||"",price:Number(s.price||pl?.price||p?.price||0),quantity:Number(s.quantity||1)}});
 return <form className="form" action="/api/admin/orders" method="post"><div className="two"><label>User*<select className="input" name="userId" required><option value="">Sélectionnez une option</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></label><label>Currency*<select className="input" name="currency" required><option value="">Select the currency</option>{currencies.map(c=><option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</select><small className="muted">Does not convert the price, only displays the currency symbol</small></label></div><label>Services</label>
 {services.map((s,i)=><div className="service-box" key={i}><button type="button" className="remove-x" onClick={()=>remove(i)} disabled={services.length===1}>🗑</button><div className="two"><label>Product*<select className="input" value={s.productId} onChange={e=>{const p=products.find(x=>String(x.id)===e.target.value);setServices(services.map((a,x)=>x===i?{...a,productId:e.target.value,planId:"",price:String(p?.price??"")}:a))}} required><option value="">Select the product</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Plan<select className="input" value={s.planId} onChange={e=>{const pl=plans.find(x=>String(x.id)===e.target.value);setServices(services.map((a,x)=>x===i?{...a,planId:e.target.value,price:String(pl?.price??a.price)}:a))}}><option value="">Select the plan</option>{plans.filter(p=>String(p.product_id)===s.productId).map(p=><option value={p.id} key={p.id}>{p.name} — {Number(p.price).toFixed(2)}</option>)}</select></label></div><div className="two"><label>Quantity*<input className="input" type="number" min="1" value={s.quantity} onChange={e=>setServices(services.map((a,x)=>x===i?{...a,quantity:e.target.value}:a))}/></label><label>Price*<input className="input" type="number" step="0.01" min="0" value={s.price} onChange={e=>setServices(services.map((a,x)=>x===i?{...a,price:e.target.value}:a))}/></label></div><label>Subscription ID<input className="input" value={s.subscriptionId} onChange={e=>setServices(services.map((a,x)=>x===i?{...a,subscriptionId:e.target.value}:a))}/></label></div>)}
 <input type="hidden" name="services" value={JSON.stringify(payload)}/><button type="button" className="btn add-service" onClick={add}>Ajouter à services</button><div className="form-actions"><button className="btn primary">Créer</button><button type="submit" className="btn" onClick={e=>{}}>Créer & Ajouter un autre</button><a className="btn" href="/admin/orders">Annuler</a></div></form>
}