"use client";
import {useState} from "react";
type Props={categories:any[];servers:any[];products:any[];initial?:any;plans?:any[];upgrades?:number[]};
export default function ProductForm({categories,servers,products,initial={},plans:initialPlans=[],upgrades:initialUpgrades=[]}:Props){
 const [tab,setTab]=useState("General");const [plans,setPlans]=useState<any[]>(initialPlans.length?initialPlans:[{name:"",type:"FREE",price:"",billingCycle:"MONTHLY",initialPrice:"",recurringPrice:""}]);const [upgrades,setUpgrades]=useState<number[]>(initialUpgrades);
 const [html,setHtml]=useState(initial.description||""); const addPlan=()=>setPlans([...plans,{name:"",type:"FREE",price:"",billingCycle:"MONTHLY",initialPrice:"",recurringPrice:""}]);
 const setPlan=(i:number,k:string,v:string)=>setPlans(plans.map((p,x)=>x===i?{...p,[k]:v}:p)); const removePlan=(i:number)=>setPlans(plans.filter((_,x)=>x!==i));
 return <form className="product-editor" action={initial.id?`/api/admin/products/${initial.id}`:"/api/admin/products"} method="post"><input type="hidden" name="_action" value={initial.id?"update":""}/><input type="hidden" name="plans" value={JSON.stringify(plans)}/><input type="hidden" name="upgrades" value={JSON.stringify(upgrades)}/>
 <div className="tabs">{["General","Pricing","Upgrades","Server"].map(t=><button type="button" key={t} className={tab===t?"tab active":"tab"} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==="General"&&<div className="editor-body"><div className="two"><label>Name*<input className="input" name="name" defaultValue={initial.name} required/></label><label>Slug*<input className="input" name="slug" defaultValue={initial.slug} required/></label></div><div className="two"><label>Stock<input className="input" name="stock" type="number" min="0" defaultValue={initial.stock??""}/></label><label>Per user limit<input className="input" name="perUserLimit" type="number" min="1" defaultValue={initial.per_user_limit??""}/></label></div><div className="two"><label>Allow quantity*<select className="input" name="allowQuantity" defaultValue={initial.allow_quantity||"SEPARATED"}><option value="SEPARATED">Separated</option><option value="COMBINED">Combined</option></select></label><label>Email template<textarea className="input" name="emailTemplate" defaultValue={initial.email_template||""}/></label></div><label className="checkline"><input type="checkbox" name="hideProduct" value="1" defaultChecked={initial.hide_product===1}/> Hide product <span className="muted">Hide the product from the client area.</span></label><label>Description <span className="html-badge">HTML</span><div className="html-toolbar"><b>B</b><i>I</i><u>U</u><span>H₂</span><span>H₃</span><span>🔗</span><span>☷</span><span>↶</span><span>↷</span><span className="html-mode">HTML source</span></div><textarea className="input rich-editor html-source-editor" value={html} onChange={e=>setHtml(e.target.value)} name="description" placeholder="Collez ou écrivez directement votre code HTML..."/></label><div className="two"><label>Image<input className="input" name="imageUrl" defaultValue={initial.image_url||""} placeholder="URL de l'image"/></label><label>Category*<select className="input" name="categoryId" defaultValue={initial.category_id||""} required><option value="">Sélectionnez une option</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div><div className="two"><label>Short description<input className="input" name="shortDescription" defaultValue={initial.short_description||""}/></label><label>Featured<select className="input" name="featured" defaultValue={String(initial.featured??0)}><option value="0">No</option><option value="1">Yes</option></select></label></div><label>Visible<select className="input" name="visible" defaultValue={String(initial.visible??1)}><option value="1">Yes</option><option value="0">No</option></select></label></div>}
 {tab==="Pricing"&&<div className="editor-body"><h3>Plans</h3><div className="plan-tools">Tout plier　 Tout déplier</div>{plans.map((p,i)=><div className="plan-card" key={i}><div className="plan-head"><span>↕</span><div><button type="button">📋</button><button type="button" className="danger-text" onClick={()=>removePlan(i)}>🗑</button><span>⌃</span></div></div><div className="two"><label>Name*<input className="input" value={p.name} onChange={e=>setPlan(i,"name",e.target.value)}/></label><label>Type*<select className="input" value={p.type} onChange={e=>setPlan(i,"type",e.target.value)}><option value="FREE">Free</option><option value="PAID">Paid</option></select></label></div><div className="two"><label>Price<input className="input" type="number" step="0.01" value={p.price} onChange={e=>setPlan(i,"price",e.target.value)}/></label><label>Billing cycle<select className="input" value={p.billingCycle} onChange={e=>setPlan(i,"billingCycle",e.target.value)}><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="YEARLY">Yearly</option><option value="ONE_TIME">One time</option></select></label></div></div>)}<button type="button" className="btn add-service" onClick={addPlan}>Add new plan</button></div>}
 {tab==="Upgrades"&&<div className="editor-body"><label>Upgrades<select className="input multi-select" multiple value={upgrades.map(String)} onChange={e=>setUpgrades(Array.from(e.target.selectedOptions).map(o=>Number(o.value)))}>{products.filter(p=>p.id!==initial.id).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><small className="muted">Sélectionnez les produits vers lesquels ce produit peut être amélioré.</small></div>}
 {tab==="Server"&&<div className="editor-body"><label>Server<select className="input" name="serverId" defaultValue={initial.server_id||""}><option value="">Sélectionnez une option</option>{servers.map(s=><option value={s.id} key={s.id}>{s.name} — {s.type}</option>)}</select></label></div>}
 <div className="form-actions"><button className="btn primary">{initial.id?"Enregistrer":"Créer"}</button><button type="submit" className="btn">Créer & Ajouter un autre</button><a className="btn" href="/admin/products">Annuler</a></div></form>
}